[build]
  publish = "dist"  # Replace with your actual publish directory
  command = "npm run build"  # Replace with your build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
